cmake_minimum_required(VERSION 3.1.0)
set(CMAKE_INCLUDE_CURRENT_DIR ON)
set(CMAKE_AUTOMOC ON)

if(CMAKE_VERSION VERSION_LESS "3.7.0")
    set(CMAKE_INCLUDE_CURRENT_DIR ON)
endif()

if(NOT QV_QT_LIBNAME)
    set(QV_QT_LIBNAME Qt5)
endif()

set(PLUGIN_INTERFACE_HEADERS
    #${QVPLUGIN_HTTP_TO_SOCKS_FILES}
    #${CMAKE_CURRENT_LIST_DIR}/PluginBase.hpp
    ${CMAKE_CURRENT_LIST_DIR}/PluginInterface.h)
set(PLUGIN_INTERFACE_INCLUDE_DIR ${CMAKE_CURRENT_LIST_DIR})